# Generated by Django 5.0.7 on 2024-07-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_profile_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='desc',
        ),
    ]
